export const apiResponses = {
    "password must be longer than or equal to 8 characters": "La contraseña debe tener al menos 8 caracteres",
    "Email registered in tattoo artist": "El correo ya está registrado en un artista tatuador",
    "Email not verified": "Correo no verificado, por favor revisa tu correo",
    "User not found": "Correo y/o contraseña incorrectos",
    "Invalid password": "Correo y/o contraseña incorrectos",
    "User already qualified": "Ya has calificado a este artista",
    "address must be longer than or equal to 3 characters": "La dirección debe tener al menos 3 caracteres",
    "description must be longer than or equal to 3 characters": "La descripción debe tener al menos 3 caracteres",
    "instagram must be longer than or equal to 3 characters": "Instagram debe tener al menos 3 caracteres",
    "facebook must be longer than or equal to 3 characters": "Facebook debe tener al menos 3 caracteres",
    "Unauthorized artist": "Artista no autorizado",
    "Unauthorized user": "Usuario no autorizado",
    "You must sign in using Google to continue": "Ya tienes una cuenta registrada con este correo, por favor inicia sesión con Google",
    "Email registered in user": "El correo ya está registrado con Google",
}
